Notebook for webscraping practice

In [2]:
#load in the file from scraping.
import json
import pandas as pd
books = pd.read_json('booksdata.json')

In [3]:
books

,url,title,upc,product_type,price_excl_tax,price_incl_tax,tax,availability,num_reviews,stars,category,description,price
0,https://books.toscrape.com/catalogue/rip-it-up...,Rip it Up and Start Again,a,books,35.02,35.02,0,19,0,5,music,"[Punk's raw power rejuvenated rock, but by the...",35.02
1,https://books.toscrape.com/catalogue/the-dirty...,The Dirty Little Secrets of Getting Your Dream...,2,books,33.34,33.34,0,19,0,4,business,[Drawing on his extensive experience evaluatin...,33.34
2,https://books.toscrape.com/catalogue/the-requi...,The Requiem Red,f,books,22.65,22.65,0,19,0,1,young adult,[Patient Twenty-nine.A monster roams the halls...,22.65
3,https://books.toscrape.com/catalogue/set-me-fr...,Set Me Free,c,books,17.46,17.46,0,19,0,5,young adult,[Aaron Ledbetter’s future had been planned out...,17.46
4,https://books.toscrape.com/catalogue/shakespea...,Shakespeare's Sonnets,3,books,20.66,20.66,0,19,0,4,poetry,[This book is an important and complete collec...,20.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,https://books.toscrape.com/catalogue/fighting-...,Fighting Fate (Fighting #6),6,books,39.24,39.24,0,1,0,3,romance,[***BONUS CONTENT: The first two chapters of J...,39.24
996,https://books.toscrape.com/catalogue/1st-to-di...,1st to Die (Women's Murder Club #1),f,books,53.98,53.98,0,1,0,1,mystery,"[James Patterson, bestselling author of the Al...",53.98
997,https://books.toscrape.com/catalogue/forever-r...,Forever Rockers (The Rocker #12),e,books,28.80,28.80,0,1,0,3,music,[My Happily Ever After was turning into a livi...,28.80
998,https://books.toscrape.com/catalogue/frankenst...,Frankenstein,a,books,38.00,38.00,0,1,0,2,default,[Mary Shelley began writing Frankenstein when ...,38.00
999,https://books.toscrape.com/catalogue/1000-plac...,"1,000 Places to See Before You Die",2,books,26.08,26.08,0,1,0,5,travel,"[Around the World, continent by continent, her...",26.08

In [5]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   url             1000 non-null   object
 1   title           1000 non-null   object
 2   upc             1000 non-null   object
 3   product_type    1000 non-null   object
 4   price_excl_tax  1000 non-null   float64
 5   price_incl_tax  1000 non-null   float64
 6   tax             1000 non-null   int64
 7   availability    1000 non-null   int64
 8   num_reviews     1000 non-null   int64
 9   stars           1000 non-null   int64
 10  category        1000 non-null   object
 11  description     1000 non-null   object
 12  price           1000 non-null   float64
dtypes: float64(3), int64(4), object(6)
memory usage: 101.7+ KB

Let's build some machine learning algorithims and pipelines

In [ ]:
y_variable = books.price
data = books.drop(columns= ['price'])
#write out some machine learning algo 
machine_algo_1 = ['DT', 'RF'] #decision tree, logistic regression, linear regression
metrics_to_measure = ['accuracy', 'roc_auc']


continuous_variables = data.select_dtypes(include=['int', 'float'])
categorical_variables =data.select_dtypes(include  = ['object'])